credentials:
  rasa_addons.core.channels.webchat.WebchatInput:
    session_persistence: true
    base_url: http://localhost:8888
    socketio_path: /development/socket.io/
    socket_path: /development/socket.io/
instance: http://rasa-development:5005
bfApiHost: http://admin-api:8080
endpoints:
  nlg:
    type: rasa_addons.core.nlg.GraphQLNaturalLanguageGenerator
    url: http://admin:3000/graphql
  action_endpoint:
    url: http://actions:5055/webhook
  tracker_store:
    store_type:  rasa_addons.core.tracker_stores.botfront.BotfrontTrackerStore
    url: http://admin:3000/graphql
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size: [32, 64]
  - name: RulePolicy
  - name: AugmentedMemoizationPolicy
defaultDomain:
  slots:
    disambiguation_message:
      type: text
      influence_conversation: false
    firstname:
      type: text
      influence_conversation: false
    language:
      type: text
      influence_conversation: false
    version:
      type: text
      influence_conversation: false
  actions:
    - action_botfront_disambiguation
    - action_botfront_disambiguation_followup
    - action_botfront_fallback
    - action_botfront_mapping
    - action_clarity_default_slots
webhooks:
  restartRasaWebhook:
    name: RestartRasa
    url: ''
    method: POST
  uploadImageWebhook:
    name: UploadImage
    url: ''
    method: POST
  deleteImageWebhook:
    name: DeleteImage
    url: ''
    method: DELETE
  deploymentWebhook:
    name: DeployProject
    url: ''
    method: POST
  reportCrashWebhook:
    name: ReportCrash
    url: ''
    method: POST
  postTraining:
    name: PostTraining
    url: ''
    method: POST
