title: Clai
subtitle: Happy to help
inputTextFieldHint: Type your message...
initPayload: /get_started
closePayload: /close
tooltipFontSize: 15
tooltipBorderSize: 0
hideWhenNotConnected: true
Widgetitlefont: 15
WidgetSubtitlefont: 12
AssistantconvFont: 15
UserconvFont: 15
